### PR TITLE
Update Readme.md

### PR DESCRIPTION
**Pull request by KR0SIV**
Tested oneplus one android phone and fixed spelling issue within the readme file.

### CODE REVIEW

**Comment by demantz** [comment]
thanks! Good to hear it works on the oneplus one!

**Comment by theoneandonly-vector** [comment]
I wrote you that a half year ago..
Am 29.06.2015 14:27 schrieb "Dennis Mantz" <notifications@github.com>:

**Comment by demantz** [comment]
@theoneandonly-vector you're right, sorry about that! Seems like I forgot to update the list and then forgot about it completely. Happens to me way too often.. this list is far from being complete.

I guess it's a bit late, but still: Thank you too! ;)

**Comment by theoneandonly-vector** [comment]
no problem ;D
Am 29.06.2015 15:12 schrieb "Dennis Mantz" <notifications@github.com>:

**Pull request merged**
